source 'https://supermarket.chef.io/'

cookbook 'apt', '= 3.0.0'
cookbook 'ark', '= 1.2.0'
cookbook 'build-essential', '= 3.2.0'
cookbook 'homebrew', '= 2.1.2'
cookbook 'nodejs', '~> 2.4.4'
cookbook 'ohai', '= 3.0.1'
cookbook 'yum', '= 3.13.0'
cookbook 'yum-epel', '= 0.7.1'
